import React,{useEffect,useState} from 'react';
import {AnimatedSection,Card,CardGrid,EngineCard,Tabs,TabPanel,ProcessButton,ScoreBadge,Reveal,StepIndicator,ConscioMascot,OutputCard} from '../components';
const engines=[['CONSCIO','01','Intent and conversational drift detection'],['SENTINEL','02','Continuous behavioral monitoring'],['OMNITRAX','03','Trace provenance and evidence graph'],['ATA-CONT','04','Constraint and doctrine evaluation'],['REPHRASE','05','Adversarial prompt resilience'],['CODEX','06','Policy-aware code review signals']];
export default function Home({navigate}){const [domain,setDomain]=useState('Operations');const [pipelineStep,setPipelineStep]=useState(0);useEffect(()=>{const id=setInterval(()=>setPipelineStep(step=>(step+1)%5),1500);return()=>clearInterval(id)},[]);return <>
<section className="page hero"><div><span className="kicker">AI governance evidence layer</span><h1>See the gap<br/>before it <em>scales.</em></h1><p className="lede">Misalignment Platform turns intent, behavior, and context into observable evidence—so teams can make better AI decisions with provenance, not assumptions.</p><div className="hero-actions"><ProcessButton onClick={()=>navigate('/demo')}>Run the interactive demo</ProcessButton><a className="button-quiet" href="#/doctrine">Read the doctrine →</a></div></div><div className="pipeline"><div className="pipeline-title"><span>Live observation pipeline</span><span>v12.4</span></div><OutputCard title="Alignment pipeline" eyebrow={['Input','Awareness','Misalignment','V12','Doctrine'][pipelineStep]}><StepIndicator steps={['Input','Awareness','Misalignment','V12','Doctrine']} current={pipelineStep}/><ConscioMascot mood={pipelineStep===2?'alert':'calm'}/></OutputCard><div className="pipeline-steps">{['Intent captured','Context normalized','Doctrine evaluated','Evidence scored','Decision surfaced'].map((x,i)=><div className="pipeline-node" key={x}><i className={i===pipelineStep?'active':''}/><span>{x}</span><small>{['12ms','34ms','41ms','18ms','ready'][i]}</small></div>)}</div><ScoreBadge score="86" label="decision support"/><p style={{color:'var(--muted)',fontSize:'.78rem',margin:'1rem 0 0'}}>Every score links back to a traceable observation.</p></div></section>
<AnimatedSection className="section"><div className="section-heading"><div><span className="eyebrow">What we do</span><h2>Make invisible drift legible.</h2></div><p>One evidence layer for the moments where an AI system's output, incentives, and operating doctrine diverge.</p></div><CardGrid>{[['◌','Observe','Capture interaction traces and operational context without interrupting the workflow.'],['⌁','Interpret','Connect signals across intent, policy, and behavior to expose meaningful patterns.'],['↗','Decide','Give humans defensible evidence and calibrated confidence for the next action.'],['◈','Provenance','Keep the why behind every finding, score, and escalation.'],['△','Continuity','Monitor change over time—not just one evaluation snapshot.'],['✦','Doctrine','Encode what your organization will and will not delegate to machines.']].map(([icon,t,p])=><Card key={t} icon={icon} title={t}><p>{p}</p></Card>)}</CardGrid></AnimatedSection>
<section className="section band"><div className="section-heading"><div><span className="eyebrow">Engine suite</span><h2>Composable by design.</h2></div><a className="text-link" href="#/engines">View all engines →</a></div><CardGrid>{engines.map(([n,c,d])=><EngineCard key={n} name={n} code={c} description={d} onClick={()=>navigate(`/engines/${n.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`)}/>)}</CardGrid></section>
<section className="section"><div className="split"><div><span className="eyebrow">Interactive demo</span><h2>From trace to decision packet.</h2><p style={{color:'var(--muted)'}}>Watch a deterministic V12 observation move through awareness, misalignment analysis, and doctrine checks.</p><ProcessButton onClick={()=>navigate('/demo')}>Explore a sample trace</ProcessButton></div><div className="notice"><span className="eyebrow">Sample observation</span><p>“The support agent resolved the ticket, but quietly broadened account permissions to improve future response time.”</p><span className="text-link">6 evidence links · 1 conflict detected</span></div></div></section>
<section className="section band"><div className="section-heading"><div><span className="eyebrow">Built for the operating reality</span><h2>Signals where stakes are real.</h2></div></div><Tabs items={['Operations','Product','Security','Research']} active={domain} onChange={setDomain}/><TabPanel active={domain==='Operations'}><div className="split"><Card title="Escalation confidence"><p>Prioritize human review with evidence-backed severity and calibrated confidence.</p></Card><Card title="Shift detection"><p>Compare current behavior to the operating envelope your team approved.</p></Card></div></TabPanel><TabPanel active={domain==='Product'}><div className="notice">Turn model behavior into product telemetry your teams can act on before a launch.</div></TabPanel><TabPanel active={domain==='Security'}><div className="notice">Connect policy triggers to trace-level evidence and incident response workflows.</div></TabPanel><TabPanel active={domain==='Research'}><div className="notice">Run repeatable experiments with stable observations and provenance.</div></TabPanel></section>
<section className="section"><div className="split"><div><span className="eyebrow">The doctrine</span><h2>A system of boundaries, made executable.</h2><p style={{color:'var(--muted)'}}>The Ata-Cont doctrine gives Conscio a clear frame for agency, truth, impact, and stewardship.</p><a className="text-link" href="#/doctrine">Explore doctrine rules →</a></div><Reveal><div className="quote">“A score is a signal to investigate—not a substitute for judgment.”<small style={{display:'block',color:'var(--muted)',marginTop:'.8rem'}}>— Misalignment Platform operating principle</small></div></Reveal></div></section>
<section className="section band"><div className="split"><div><span className="eyebrow">Partner program</span><h2>Make evidence part of the stack.</h2></div><div><p style={{color:'var(--muted)'}}>For platforms, integrators, and researchers building trustworthy AI operations.</p><a className="text-link" href="#/partners">See partner paths →</a></div></div></section>
<section className="section"><div className="split"><div><span className="eyebrow">Founder vision</span><h2>Governance should be observable.</h2></div><div><p style={{color:'var(--muted)'}}>Built by Brianel Hunter after decades in utility operations, where safe decisions depend on seeing weak signals early.</p><a className="text-link" href="#/about">Read our story →</a></div></div></section>
<section className="section"><div className="notice" style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'1rem',flexWrap:'wrap'}}><div><span className="eyebrow">Early access</span><h2 style={{margin:'.4rem 0'}}>Bring your hardest AI workflow.</h2><p style={{color:'var(--muted)',margin:0}}>We will map the evidence you need to make the next decision.</p></div><ProcessButton onClick={()=>navigate('/early-access')}>Request access</ProcessButton></div></section>
</>}
